#!/bin/bash
### BEGIN INIT INFO
# Provides: omxplayer
### END INIT INFO

#Cameras
camera1='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'
camera2='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'
camera3='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'
camera4='rtsp://user:pass@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1\&subtype=1'

# ------------- Use extreme caution when editing below this line ---------------------------
#Screen Control
case "$1" in
  cam1)
    screen -dmS stream2 sh -c 'omxplayer '$camera1' -b --live; exec bash'
    /home/pi/cgi-bin/./2tone
    ;;
  cam2)
    screen -dmS stream3 sh -c 'omxplayer '$camera2' -b --live; exec bash'
    /home/pi/cgi-bin/./2tone
    ;;
  cam3)
    screen -dmS stream4 sh -c 'omxplayer '$camera3' -b --live; exec bash'
    /home/pi/cgi-bin/./2tone
    ;;
  cam4)
    screen -dmS stream5 sh -c 'omxplayer '$camera4' -b --live; exec bash'
    /home/pi/cgi-bin/./2tone
    ;;
  camStop)
    screen -X -S stream2 quit
    screen -X -S stream3 quit
    screen -X -S stream4 quit
    screen -X -S stream5 quit
    ;;
  MMstart)
    cd /home/pi/MagicMirror
    screen -dmS stream1 sh -c 'DISPLAY=:0 npm start; exec bash'
    ;;
      PFstart)
    screen -dmS stream1 sh -c 'DISPLAY=:0.0 XAUTHORITY=/home/pi/.Xauthority /usr/bin/feh -q -p -z -Z -F -R  60 -Y -D 60 /home/pi/Pictures; exec bash'
    ;;
  stop)
    screen -X -S stream1 quit
    ;;
  unclutter)
    unclutter -display :0 -idle 3 -root -noevents
    ;;

*)
exit 1
;;

esac
